### ISSUE TITLE
Badger not properly forwarding real IP's via Cloudflare

### ISSUE THREAD

**Issue by slimshizn** [fosrl/badger#6]
Placing this here as further discussion via Discord reveals badger is possibly the issue. 

More discussion here https://discord.com/channels/1325658630518865980/1325658631567573029/1378616813298126919

Original Pangolin issues:

https://github.com/fosrl/pangolin/issues/341

https://github.com/fosrl/pangolin/issues/619

**Comment by AstralDestiny** [comment]
It's because Badger is getting just the request IP and that won't be anything in the preferred X-Forwarded-For and not limited to just cloudflare, If there's any downstream or upstream reverse proxy or webserver it will get the requestIP which might be the proxy itself, 

It's due to the code doesn't look for X-Forwarded-For, The code assumes the initial request is the actual visitor ip but X-Forwarded-For includes each server that handles the request.. Been trying locally for it to get the X-Forwarded-For but not very versed in Traefik plugins exactly so stumbling around in the dark right now.

**Comment by oschwartz10612** [comment]
^^ This is correct its just grabbing the client IP and putting it into the `X` header. 

Badger would need to pull the IP from the Cloudflare provided header and send it along in the X header or something like that. Not sure if there are any security concerns with something like that...

**Comment by jghaanstra** [comment]
Could someone tell me where this is on the roadmap. There have been several major Pangolin releases but no love for Badger. To me this is a pretty serious bug rendering the Pangolin rules useless when used in combination with Cloudflare proxy. The fix isn't too complicated. For now I'm using this patched version but I'd like to see the bug fixed in the official plugin. 

https://plugins.traefik.io/plugins/68b2afa13971511800dd078c/fossorial-badger-patch-with-i-pv6

**Comment by praveenroot03** [comment]
I see that there is so many PRs and forks of the fix implementation, please look into it and fix this.

**Comment by slimshizn** [comment]
@praveenroot03 kind of odd that they've ignored this one. Your best bet is using one of the patches since they seemingly don't plan on getting to this. I'm going to close this, but it's not fixed. Someone else can open a new issue.

**Comment by yann117** [comment]
Does it make sense to close it and request that a new one be raised?

What is the point of having duplicates, except that it causes confusion when trying to get a picture of the product's state?

Milo already mentioned they will look into it (see above history), so we are not in a hurry, there are no SLA, just wait for it patiently (and keep one single report open) ?

**Comment by yann117** [comment]
> but it also doesn't make sense for it to sit open for as long as it has when PRs exist

I guess you are not a dev. On the contrary, it is just one of the basic principles of development and tracking issues.
As long as the PR is not reviewed and merged, the report remains open, indicating that it has not yet been included in the product.

The fact that you are the reporter and "moved on" doesn't make a difference here and is irrelevant.

This one is flagged as an _enhancement_, and enhancements typically have a longer lifecycle (lower priority) than bugs.

**Comment by oschwartz10612** [comment]
Pinging @miloschwartz to take a look when he is ready. Will try to merge soon 😄

**Comment by jghaanstra** [comment]
@thutex Just be aware, though my patched Badger version works, the implementation has flaws. For more info, read [this comment](https://github.com/fosrl/badger/pull/9#issuecomment-3506130372). I'm in the same boat though and choose to use it anyway as it's the only way I can use Pangolin rule engine together with Cloudflare proxy.

**Comment by yann117** [comment]
Yes, I updated and observe the same too

**Comment by overclockit** [comment]
Possibly related to logRequestAudit.ts specifically this section, could have a similar regex which should fix the issue for audit logs, I never personally tried EE features so hadn't checked beyond Badger:

```
        const clientIp = body.requestIp
            ? (() => {
                  if (
                      body.requestIp.startsWith("[") &&
                      body.requestIp.includes("]")
                  ) {
                      // if brackets are found, extract the IPv6 address from between the brackets
                      const ipv6Match = body.requestIp.match(/\[(.*?)\]/);
                      if (ipv6Match) {
                          return ipv6Match[1];
                      }
                  }

                  // ivp4
                  // split at last colon
                  const lastColonIndex = body.requestIp.lastIndexOf(":");
                  if (lastColonIndex !== -1) {
                      return body.requestIp.substring(0, lastColonIndex);
                  }
                  return body.requestIp;
              })()
            : undefined;
```

**Comment by yann117** [comment]
@overclockit You are right on it again. I can confirm it is only in Request log UI.
Previously I set up some blocking rule on my IPv6 and it was not blocking me at all (confirming it was failing at a lower layer).
Now, despite it shows the mangled IP in the Request log UI,, the rule applies properly and block the access 👍
So just a minor/cosmetic issue remains, but the feature work, thank you all!

**Comment by miloschwartz** [comment]
Well... I didn't realize just how many places we had similar code to strip the port. 🤦

I went around and replaced them all with re-usable function. You can see the code changes here. Let me know if I am still missing something. This will all come out in the 1.14.1 release.

https://github.com/fosrl/pangolin/commit/da112d3417a6ed1a0fdd9fcc46bcf0b4bd41a6a4

**Comment by onno204** [comment]
Hi both,

Thank you for the efforts of implementing Cloudflare ClientIP support and enabling it by default.

However, I am behind a non-Cloudflare proxy, so I tried to follow the documentation of "Using without Cloudflare" in the ReadMe.md
But this doesn't seem to work for me.

Tested with versions `1.3.0` and `1.3.1`.

I tried to set the settings manually in both config files (`dynamic_config.yml` and `traefik_config.yml`). But it still seems to use the proxy as ClientIP:
```
http:
  middlewares:
    badger:
      plugin:
        badger:
          apiBaseUrl: "http://192.168.6.188:3001/api/v1/traefik-config"
          userSessionCookieName: "p_session_token"
          resourceSessionRequestParam: "p_session_request"
          disableDefaultCFIPs: false # Disable Cloudflare IP ranges
          trustip: # Add your proxy/load balancer IP ranges (CIDR format)
            - "192.168.6.161/32"
          customIPHeader: "X-Forwarded-For"
```

My guess is traefik uses the dynamic config provided by the pangolin-API instead of the custom config:
GET - http://192.168.6.188:3001/api/v1/traefik-config
```
{"http":{"middlewares":{"redirect-to-https":{"redirectScheme":{"scheme":"https"}},"badger":{"plugin":{"badger":{"apiBaseUrl":"http://pangolin:3001/api/v1","userSessionCookieName":"p_session_token","accessTokenQueryParam":"p_token","resourceSessionRequestParam":"resource_session_request_param"}}}},"routers": ...
```

In the Traefik access.log, I also see it doesn't accept the proxy-ip as proxy:
```
{"ClientAddr":"192.168.6.161:35996","ClientHost":"<my-public-ip>","DownstreamContentSize":13,"DownstreamStatus":401,"Duration":3182795,"RequestMethod":"GET","RequestPath":"/favicon.ico","RequestProtocol":"HTTP/1.1","RetryAttempts":0,"StartUTC":"2025-12-25T22:30:55.669061184Z","TLSCipher":"TLS_AES_128_GCM_SHA256","TLSVersion":"1.3","downstream_Content-Type":"text/plain; charset=utf-8","level":"info","msg":"","request_Cookie":"REDACTED","request_User-Agent":"Chrome/142.0.0.0","request_X-Forwarded-For":"<my-public-ip>","request_X-Forwarded-Proto":"https","request_X-Real-Ip":"192.168.6.161","time":"2025-12-25T23:30:55+01:00"}
```

The request logs also show the incorrect IP:
<img width="1253" height="400" alt="Image" src="https://github.com/user-attachments/assets/bca68263-a246-4b7e-85ae-2109b53b0d06" />


As I am not familiar with how Traefik handles dynamic configs, is my theory correct that it uses the config provided by the pangolin API?
And if so, is there a way to make the pangolin API include the `trustip` and `customIPHeader` variables?

**Comment by onno204** [comment]
Tested a bit more; when cloning the repository, referencing it as a local plugin in Traefik, and hard-coding the variables, it is working flawlessly <3

Added hardcoded proxy IP:
<img width="517" height="279" alt="Image" src="https://github.com/user-attachments/assets/b1dce0a0-4837-4516-9acd-18677474691d" />

And first look at xForwarderFor instead of CF-RealIP:
<img width="953" height="230" alt="Image" src="https://github.com/user-attachments/assets/abc1c6d1-2a85-4c92-affd-fafa91a0b4c5" />


However, as I do wish to stay up-to-date, I prefer using the traefik-plugin instead of a local-plugin.
So my previous question remains the same.

**Comment by overclockit** [comment]
If I remember rightly, this is one of the reasons I used the Pangolin config.yml instead of dynamic_config.yml. Currently there are effectively two instances of Badger, one which is defined by Pangolin with defaults:

```
        if (traefikConfig?.http?.middlewares) {
            // BECAUSE SOMETIMES THE CONFIG CAN BE EMPTY IF THERE IS NOTHING
            traefikConfig.http.middlewares[badgerMiddlewareName] = {
                plugin: {
                    [badgerMiddlewareName]: {
                        apiBaseUrl: new URL(
                            "/api/v1",
                            `http://${
                                config.getRawConfig().server.internal_hostname
                            }:${config.getRawConfig().server.internal_port}`
                        ).href,
                        userSessionCookieName:
                            config.getRawConfig().server.session_cookie_name,

                        // deprecated
                        accessTokenQueryParam:
                            config.getRawConfig().server
                                .resource_access_token_param,

                        resourceSessionRequestParam:
                            config.getRawConfig().server
                                .resource_session_request_param
                    }
                }
            };
        }
```

Another as defined in dynamic_config.yml, this could also explain why in my testing, Badger 1.2.0 didn't work with the UI but did function with a valid cookie. Essentially it doesn't matter what we put in dynamic_config, it will continue to use Badger settings from Pangolin.

Two ways I know to address this would be 1. Use only Pangolin's config.yml for all Badger config settings or 2. Strip the above and replace const badgerMiddlewareName = "badger"; with const badgerMiddlewareName = "badger@file"; in getTraefikConfig.ts files.

I personally tested the latter and it does work as intended, the only issue I had was with a redirect loop when disabledForwardAuth is set to false, adding the following back to Pangolin's config.yml:
    internal_hostname: "pangolin"
    internal_port: 3001
    session_cookie_name: "p_session_token"
    resource_access_token_param: "p_token"
    resource_session_request_param: "p_session_request"
Additionally ensuring the following was set in dynamic_config.yml under badger fixed this in my limited testing:
          apiBaseUrl: "http://pangolin:3001/api/v1"
          userSessionCookieName: "p_session_token"
          resourceSessionRequestParam: "p_session_request"

For X-Forwarded-For specifically, we really do need to add proper parsing logic to walk the line and use either the first untrusted from right to left or the last IP if all are trusted, with logic in place for when the header is empty (direct connection). Basically use customIP := req.Header.Get(p.customIPHeader) then if customIP != "" etc. with appropriate validation, iterating from right to left.

I personally went with for testing and it works as expected:

```
	if p.customIPHeader != "" {
		fmt.Println("Badger: using custom IP header", p.customIPHeader)

		customIP := req.Header.Get(p.customIPHeader)
		if customIP != "" {
			ips := strings.Split(customIP, ",")
			for i := len(ips) - 1; i >= 0; i-- {
				ip := strings.TrimSpace(ips[i])
				if !p.isTrustedIP(ip) {
					return ip
				}
			}
			finalIp := strings.TrimSpace(ips[0])
			return finalIp
		}
	}
```
